name: Continuous Integration and Deployment

on:
  push:
    branches: 
        - main

  schedule:
    - cron: '0 */5 * * *' 

env:
    DOTNET_VERSION: '5.0.x'
    AZURE_WEBAPP_NAME: 'didierz-weather'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
 
      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build App
        run: dotnet build -c Release --no-restore

      - name: Publish App
        run: dotnet publish -c Release -o ./out

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      #- name: Deploy to Azure Web Apps
      #  uses: azure/webapps-deploy@v2
      #  with:
      #      app-name: ${{ env.AZURE_WEBAPP_NAME }}
      #      publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_SECRET }}
      #      package: ./out

      - name: Deploy to Azure Web Apps
        uses: azure/webapps-deploy@v2
        with:
            app-name: ${{ env.AZURE_WEBAPP_NAME }}
            package: ./out
        
